### ISSUE TITLE
SofaGLFW cannot be compiled

### ISSUE THREAD

**Issue by dessteph** [sofa-framework/SofaGLFW#44]
I cannot compile the plugin SofaGLFW with SofaImGUI (master branch) on Linux (Ubuntu). It seems that it can't find a library that is actually installed.

/usr/bin/ld: CMakeFiles/SofaImGui.dir/__/__/__/__/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o: in function `imgl3wInit':
imgui_impl_opengl3.cpp:(.text+0x515): undefined reference to dlopen`

**Comment by alxbilger** [comment]
@dessteph it does not work on your side, right? Could you confirm?
If it does not work, could you display the content of `CMAKE_DL_LIBS` before the line `target_link_libraries(${PROJECT_NAME} PUBLIC SofaGLFW ${CMAKE_DL_LIBS})` ? You could do `message("CMAKE_DL_LIBS: ${CMAKE_DL_LIBS}")`

@Camille-K Could you do that as well?

**Comment by dessteph** [comment]
It didn't work yesterday even with that fix. I cleared my build directory and recompiled it but the plugin, Imgui still could not be compiled. I updated my master which cannot be compiled for now (error on qt API).
